AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AzilenNestjsDevCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: azilen-nestjs-dev-cluster

  AzilenNestjsDevTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: azilen-nestjs-dev-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: <ecsTaskExecutionRoleArn>
      ContainerDefinitions:
        - Name: azilen-nestjs-dev
          Image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/azilen-nestjs-dev:latest
          PortMappings:
            - ContainerPort: 3000

  AzilenNestjsDevService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref AzilenNestjsDevCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref AzilenNestjsDevTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: [<subnet-ids>]
          SecurityGroups: [<security-group-ids>]
